name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer

      - name: Install dependencies and wrap them
        run: composer install

      - name: Remove dev dependencies and optimize autoloader
        run: composer update --no-dev --no-scripts --optimize-autoloader

      - name: WordPress deploy plugin
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
